version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "org.knowm.xchart:xchart"
        update-types: ["version-update:semver-major"]