name: build

on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Java setup
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 8

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew setupCiWorkspace
          ./gradlew build --no-daemon

      - name: Find and rename jar
        run: |
          ls -la build/libs/
          if ls build/libs/FDPClient-*.jar 1> /dev/null 2>&1; then
            mv build/libs/FDPClient-*.jar build/libs/FDPClient-build.jar
          fi
          ls -la build/libs/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: FDPClient
          path: build/libs/FDPClient-build.jar
